name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm install
        name: install dependancies
      - run: npm run test
        name: run tests
      - run: npm run lint
        name: run lint
      - run: npm run build
        name: run build
